import { Question, Level } from './types';

export const allQuestions: Record<'en' | 'es' | 'fr', Question[]> = {
  en: [
    { id: 1, text: "They ___ from Canada.", options: ["is", "are", "am"], correctAnswer: "are", level: "A1" },
    { id: 2, text: "I ___ a car.", options: ["has", "have", "am"], correctAnswer: "have", level: "A1" },
    { id: 3, text: "What time ___ it?", options: ["is", "are", "do"], correctAnswer: "is", level: "A1" },
    { id: 4, text: "She ___ to the park yesterday.", options: ["go", "goes", "went"], correctAnswer: "went", level: "A2" },
    { id: 5, text: "This is the ___ movie I've ever seen.", options: ["good", "better", "best"], correctAnswer: "best", level: "A2" },
    { id: 6, text: "I'm going ___ a doctor.", options: ["be", "to be", "being"], correctAnswer: "to be", level: "A2" },
    { id: 7, text: "There isn't ___ milk in the fridge.", options: ["some", "any", "a"], correctAnswer: "any", level: "A2" },
    { id: 8, text: "If I ___ more time, I would learn to play the guitar.", options: ["have", "had", "will have"], correctAnswer: "had", level: "B1" },
    { id: 9, text: "Have you ever ___ to Japan?", options: ["be", "been", "being"], correctAnswer: "been", level: "B1" },
    { id: 10, text: "This book was written ___ a famous author.", options: ["by", "from", "of"], correctAnswer: "by", level: "B1" },
    { id: 11, text: "I'm not used ___ up so early.", options: ["to get", "getting", "to getting"], correctAnswer: "to getting", level: "B1" },
    { id: 12, text: "___ the bad weather, the game was not cancelled.", options: ["Although", "Despite", "However"], correctAnswer: "Despite", level: "B1" },
    { id: 13, text: "He told me that he ___ the movie the night before.", options: ["sees", "has seen", "had seen"], correctAnswer: "had seen", level: "B2" },
    { id: 14, text: "You ___ have told me you were coming!", options: ["should", "would", "will"], correctAnswer: "should", level: "B2" },
    { id: 15, text: "I need to get my car ___ this weekend.", options: ["repair", "repaired", "to repair"], correctAnswer: "repaired", level: "B2" },
    { id: 16, text: "The problem was very difficult to ___.", options: ["get over", "figure out", "look up"], correctAnswer: "figure out", level: "B2" },
    { id: 17, text: "If I had known you were in town, I ___ you.", options: ["would visit", "will visit", "would have visited"], correctAnswer: "would have visited", level: "B2" },
    { id: 18, text: "Not only ___ sing, but she also plays the piano beautifully.", options: ["she can", "can she", "she does"], correctAnswer: "can she", level: "C1" },
    { id: 19, text: "He was on the ___ of leaving when the phone rang.", options: ["edge", "point", "verge"], correctAnswer: "verge", level: "C1" },
    { id: 20, text: "It's high time you ___ taking this more seriously.", options: ["start", "started", "should start"], correctAnswer: "started", level: "C1" },
  ],
  es: [
    { id: 1, text: "Mi casa ___ en el centro.", options: ["es", "soy", "está"], correctAnswer: "está", level: "A1" },
    { id: 2, text: "Ellos ___ dos perros.", options: ["tienen", "tienes", "tenemos"], correctAnswer: "tienen", level: "A1" },
    { id: 3, text: "Yo no ___ carne.", options: ["como", "comes", "come"], correctAnswer: "como", level: "A1" },
    { id: 4, text: "Ayer, nosotros ___ al cine.", options: ["vamos", "fuimos", "iban"], correctAnswer: "fuimos", level: "A2" },
    { id: 5, text: "Este coche es más ___ que el tuyo.", options: ["rápido", "rapidez", "rápidamente"], correctAnswer: "rápido", level: "A2" },
    { id: 6, text: "Me ___ levantarme temprano.", options: ["gusta", "gustan", "gusto"], correctAnswer: "gusta", level: "A2" },
    { id: 7, text: "Mañana voy a ___ a mi abuela.", options: ["visitar", "visito", "visitando"], correctAnswer: "visitar", level: "A2" },
    { id: 8, text: "Cuando era niño, ___ mucho en el parque.", options: ["jugué", "jugaba", "juego"], correctAnswer: "jugaba", level: "B1" },
    { id: 9, text: "Si yo ___ rico, compraría una isla.", options: ["era", "fui", "fuera"], correctAnswer: "fuera", level: "B1" },
    { id: 10, text: "La carta fue ___ por el director.", options: ["escrito", "escribió", "escrita"], correctAnswer: "escrita", level: "B1" },
    { id: 11, text: "Te recomiendo que ___ más agua.", options: ["bebes", "bebas", "beber"], correctAnswer: "bebas", level: "B1" },
    { id: 12, text: "Me molesta que la gente no ___ puntual.", options: ["es", "sea", "son"], correctAnswer: "sea", level: "B1" },
    { id: 13, text: "Cuando llegué a la estación, el tren ya se ___.", options: ["fue", "había ido", "iba"], correctAnswer: "había ido", level: "B2" },
    { id: 14, text: "Si ___ estudiado más, habrías aprobado el examen.", options: ["habías", "hubieras", "has"], correctAnswer: "hubieras", level: "B2" },
    { id: 15, text: "El libro ___ estoy leyendo es muy interesante.", options: ["que", "cual", "cuyo"], correctAnswer: "que", level: "B2" },
    { id: 16, text: "Espero que ___ buen tiempo mañana.", options: ["hace", "haga", "hará"], correctAnswer: "haga", level: "B2" },
    { id: 17, text: "El artista, ___ obras son famosas, visitará la ciudad.", options: ["cuyas", "que", "cuales"], correctAnswer: "cuyas", level: "C1" },
    { id: 18, text: "Se me ___ las llaves en casa esta mañana.", options: ["olvidó", "olvidaron", "olvidaste"], correctAnswer: "olvidaron", level: "C1" },
    { id: 19, text: "Por mucho que ___, no cambiaré de opinión.", options: ["insistes", "insistas", "insistir"], correctAnswer: "insistas", level: "C1" },
    { id: 20, text: "Apenas ___ llegado cuando empezó a llover.", options: ["había", "he", "hubo"], correctAnswer: "había", level: "C1" },
  ],
  fr: [
    { id: 1, text: "Vous ___ professeur?", options: ["sont", "êtes", "avez"], correctAnswer: "êtes", level: "A1" },
    { id: 2, text: "Il ___ à Paris.", options: ["habite", "habites", "habitons"], correctAnswer: "habite", level: "A1" },
    { id: 3, text: "Nous ___ au cinéma ce soir.", options: ["allons", "allez", "vont"], correctAnswer: "allons", level: "A1" },
    { id: 4, text: "Hier, j'ai ___ un bon film.", options: ["regardé", "regarde", "regarder"], correctAnswer: "regardé", level: "A2" },
    { id: 5, text: "C'est la ___ belle ville de France.", options: ["plus", "très", "beaucoup"], correctAnswer: "plus", level: "A2" },
    { id: 6, text: "Je voudrais ___ de l'eau, s'il vous plaît.", options: ["un", "une", "de la"], correctAnswer: "de la", level: "A2" },
    { id: 7, text: "Je vais ___ mes devoirs demain.", options: ["fais", "faire", "fait"], correctAnswer: "faire", level: "A2" },
    { id: 8, text: "Si j'avais le temps, je ___ au Japon.", options: ["vais", "irais", "suis allé"], correctAnswer: "irais", level: "B1" },
    { id: 9, text: "Le livre a été ___ par un auteur célèbre.", options: ["écrit", "écrire", "écrivait"], correctAnswer: "écrit", level: "B1" },
    { id: 10, text: "Quand j'étais petit, je ___ le chocolat.", options: ["aime", "ai aimé", "aimais"], correctAnswer: "aimais", level: "B1" },
    { id: 11, text: "Il faut que tu ___ plus attentif.", options: ["es", "sois", "être"], correctAnswer: "sois", level: "B1" },
    { id: 12, text: "C'est le meilleur film que je n'aie jamais ___.", options: ["vu", "vois", "voyais"], correctAnswer: "vu", level: "B2" },
    { id: 13, text: "Bien qu'il ___ fatigué, il a continué à travailler.", options: ["est", "était", "soit"], correctAnswer: "soit", level: "B2" },
    { id: 14, text: "Si j'avais su, je ___ venu plus tôt.", options: ["serais", "étais", "serai"], correctAnswer: "serais", level: "B2" },
    { id: 15, text: "Le garçon ___ les parents sont avocats est mon ami.", options: ["que", "qui", "dont"], correctAnswer: "dont", level: "B2" },
    { id: 16, text: "Je te le dis pour que tu ___ la vérité.", options: ["sais", "sauras", "saches"], correctAnswer: "saches", level: "B2" },
    { id: 17, text: "Après ___ le film, nous sommes rentrés.", options: ["avoir vu", "voir", "voyant"], correctAnswer: "avoir vu", level: "C1" },
    { id: 18, text: "Il s'est ___ compte de son erreur trop tard.", options: ["fait", "donné", "rendu"], correctAnswer: "rendu", level: "C1" },
    { id: 19, text: "Il est parti sans que personne ne ___ aperçoive.", options: ["s'en est", "s'en", "s'en soit"], correctAnswer: "s'en", level: "C1" },
    { id: 20, text: "Je regrette que vous ___ si vite.", options: ["partez", "partiez", "êtes parti"], correctAnswer: "partiez", level: "C1" },
  ]
};

export const proficiencyLevels: Level[] = [
    { name: "Iniciante", level: "A1", description: "Consegue entender e usar expressões familiares e cotidianas.", minCorrect: 0 },
    { name: "Básico", level: "A2", description: "Consegue comunicar em tarefas simples e rotineiras, descrevendo aspectos do seu passado.", minCorrect: 7 },
    { name: "Intermediário", level: "B1", description: "Lida com a maioria das situações em viagens, descreve experiências e ambições.", minCorrect: 12 },
    { name: "Intermediário-Avançado", level: "B2", description: "Consegue entender ideias complexas e interagir com um grau de fluência com falantes nativos.", minCorrect: 16 },
    { name: "Avançado", level: "C1", description: "Parabéns! Você se expressa de forma fluente e espontânea, usando a língua de forma flexível e eficaz.", minCorrect: 19 },
];